# Generated by Django 4.0.10 on 2023-05-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firm_info', '0003_firmcontact_baseline_firmcontact_short_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmcontact',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='firm/logo'),
        ),
        migrations.AddField(
            model_name='firmcontact',
            name='logo_invert',
            field=models.ImageField(blank=True, null=True, upload_to='firm/logo_inverted'),
        ),
    ]
