# Generated by Django 4.0.10 on 2023-06-02 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firm_info', '0007_socialsharing_tracking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tracking',
            options={'verbose_name': 'Tracking', 'verbose_name_plural': 'Tracks'},
        ),
    ]
