# Generated by Django 5.1.5 on 2026-03-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firm_info", "0012_alter_appsbanner_application_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="firmcontact",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Latitude",
            ),
        ),
        migrations.AddField(
            model_name="firmcontact",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Longitude",
            ),
        ),
    ]
