on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  workflow_run:
    workflows: [Test]
    branches: [master]
    types: [completed]

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create a Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: CHANGELOG.rst
          token: ${{ secrets.GITHUB_TOKEN }}

